// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: twt.proto

package twtproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProxyComm_MessageType int32

const (
	ProxyComm_DATA_DOWN    ProxyComm_MessageType = 0 // downlink data, presumably most frequent message type
	ProxyComm_DATA_UP      ProxyComm_MessageType = 1 // uplink data
	ProxyComm_ACK_DOWN     ProxyComm_MessageType = 2 // acknowledge reception of downlink data
	ProxyComm_ACK_UP       ProxyComm_MessageType = 3 // acknowledge reception of uplink data
	ProxyComm_OPEN_CONN    ProxyComm_MessageType = 4 // open remote connection to server
	ProxyComm_CLOSE_CONN_S ProxyComm_MessageType = 5 // close remote connection to server
	ProxyComm_CLOSE_CONN_C ProxyComm_MessageType = 6 // close local connection to client
	ProxyComm_PING         ProxyComm_MessageType = 7 // ping
)

// Enum value maps for ProxyComm_MessageType.
var (
	ProxyComm_MessageType_name = map[int32]string{
		0: "DATA_DOWN",
		1: "DATA_UP",
		2: "ACK_DOWN",
		3: "ACK_UP",
		4: "OPEN_CONN",
		5: "CLOSE_CONN_S",
		6: "CLOSE_CONN_C",
		7: "PING",
	}
	ProxyComm_MessageType_value = map[string]int32{
		"DATA_DOWN":    0,
		"DATA_UP":      1,
		"ACK_DOWN":     2,
		"ACK_UP":       3,
		"OPEN_CONN":    4,
		"CLOSE_CONN_S": 5,
		"CLOSE_CONN_C": 6,
		"PING":         7,
	}
)

func (x ProxyComm_MessageType) Enum() *ProxyComm_MessageType {
	p := new(ProxyComm_MessageType)
	*p = x
	return p
}

func (x ProxyComm_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProxyComm_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_twt_proto_enumTypes[0].Descriptor()
}

func (ProxyComm_MessageType) Type() protoreflect.EnumType {
	return &file_twt_proto_enumTypes[0]
}

func (x ProxyComm_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProxyComm_MessageType.Descriptor instead.
func (ProxyComm_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_twt_proto_rawDescGZIP(), []int{0, 0}
}

type ProxyComm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mt            ProxyComm_MessageType  `protobuf:"varint,1,opt,name=mt,proto3,enum=twtproto.ProxyComm_MessageType" json:"mt,omitempty"`
	Proxy         uint64                 `protobuf:"varint,2,opt,name=proxy,proto3" json:"proxy,omitempty"`           // id of the proxy which is sending the message, must by globally unique
	Connection    uint64                 `protobuf:"varint,3,opt,name=connection,proto3" json:"connection,omitempty"` // sequential number of the connection on the local side of the proxy
	Seq           uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`               // sequential number of the message within the connection, sequential numbers are independent per up/down directions
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`        // remote address to connect to, only used in OPEN_CONN message
	Port          uint32                 `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`             // remote port to connect to, only used in OPEN_CONN message
	Data          []byte                 `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`              // data chunk, only used in DATA_* messages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyComm) Reset() {
	*x = ProxyComm{}
	mi := &file_twt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyComm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyComm) ProtoMessage() {}

func (x *ProxyComm) ProtoReflect() protoreflect.Message {
	mi := &file_twt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyComm.ProtoReflect.Descriptor instead.
func (*ProxyComm) Descriptor() ([]byte, []int) {
	return file_twt_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyComm) GetMt() ProxyComm_MessageType {
	if x != nil {
		return x.Mt
	}
	return ProxyComm_DATA_DOWN
}

func (x *ProxyComm) GetProxy() uint64 {
	if x != nil {
		return x.Proxy
	}
	return 0
}

func (x *ProxyComm) GetConnection() uint64 {
	if x != nil {
		return x.Connection
	}
	return 0
}

func (x *ProxyComm) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ProxyComm) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ProxyComm) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ProxyComm) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_twt_proto protoreflect.FileDescriptor

const file_twt_proto_rawDesc = "" +
	"\n" +
	"\ttwt.proto\x12\btwtproto\"\xc9\x02\n" +
	"\tProxyComm\x12/\n" +
	"\x02mt\x18\x01 \x01(\x0e2\x1f.twtproto.ProxyComm.MessageTypeR\x02mt\x12\x14\n" +
	"\x05proxy\x18\x02 \x01(\x04R\x05proxy\x12\x1e\n" +
	"\n" +
	"connection\x18\x03 \x01(\x04R\n" +
	"connection\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x06 \x01(\rR\x04port\x12\x12\n" +
	"\x04data\x18\a \x01(\fR\x04data\"\x80\x01\n" +
	"\vMessageType\x12\r\n" +
	"\tDATA_DOWN\x10\x00\x12\v\n" +
	"\aDATA_UP\x10\x01\x12\f\n" +
	"\bACK_DOWN\x10\x02\x12\n" +
	"\n" +
	"\x06ACK_UP\x10\x03\x12\r\n" +
	"\tOPEN_CONN\x10\x04\x12\x10\n" +
	"\fCLOSE_CONN_S\x10\x05\x12\x10\n" +
	"\fCLOSE_CONN_C\x10\x06\x12\b\n" +
	"\x04PING\x10\aB\x15Z\x13palecci.cz/twtprotob\x06proto3"

var (
	file_twt_proto_rawDescOnce sync.Once
	file_twt_proto_rawDescData []byte
)

func file_twt_proto_rawDescGZIP() []byte {
	file_twt_proto_rawDescOnce.Do(func() {
		file_twt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_twt_proto_rawDesc), len(file_twt_proto_rawDesc)))
	})
	return file_twt_proto_rawDescData
}

var file_twt_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_twt_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_twt_proto_goTypes = []any{
	(ProxyComm_MessageType)(0), // 0: twtproto.ProxyComm.MessageType
	(*ProxyComm)(nil),          // 1: twtproto.ProxyComm
}
var file_twt_proto_depIdxs = []int32{
	0, // 0: twtproto.ProxyComm.mt:type_name -> twtproto.ProxyComm.MessageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_twt_proto_init() }
func file_twt_proto_init() {
	if File_twt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_twt_proto_rawDesc), len(file_twt_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_twt_proto_goTypes,
		DependencyIndexes: file_twt_proto_depIdxs,
		EnumInfos:         file_twt_proto_enumTypes,
		MessageInfos:      file_twt_proto_msgTypes,
	}.Build()
	File_twt_proto = out.File
	file_twt_proto_goTypes = nil
	file_twt_proto_depIdxs = nil
}
