// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: twt.proto

package twtproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProxyComm_MessageType int32

const (
	ProxyComm_DATA_DOWN    ProxyComm_MessageType = 0 // downlink data, presumably most frequent message type
	ProxyComm_DATA_UP      ProxyComm_MessageType = 1 // uplink data
	ProxyComm_OPEN_CONN    ProxyComm_MessageType = 2 // open remote connection to server
	ProxyComm_CLOSE_CONN_S ProxyComm_MessageType = 3 // close remote connection to server
	ProxyComm_CLOSE_CONN_C ProxyComm_MessageType = 4 // close local connection to client
	ProxyComm_PING         ProxyComm_MessageType = 5 // ping
)

// Enum value maps for ProxyComm_MessageType.
var (
	ProxyComm_MessageType_name = map[int32]string{
		0: "DATA_DOWN",
		1: "DATA_UP",
		2: "OPEN_CONN",
		3: "CLOSE_CONN_S",
		4: "CLOSE_CONN_C",
		5: "PING",
	}
	ProxyComm_MessageType_value = map[string]int32{
		"DATA_DOWN":    0,
		"DATA_UP":      1,
		"OPEN_CONN":    2,
		"CLOSE_CONN_S": 3,
		"CLOSE_CONN_C": 4,
		"PING":         5,
	}
)

func (x ProxyComm_MessageType) Enum() *ProxyComm_MessageType {
	p := new(ProxyComm_MessageType)
	*p = x
	return p
}

func (x ProxyComm_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProxyComm_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_twt_proto_enumTypes[0].Descriptor()
}

func (ProxyComm_MessageType) Type() protoreflect.EnumType {
	return &file_twt_proto_enumTypes[0]
}

func (x ProxyComm_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProxyComm_MessageType.Descriptor instead.
func (ProxyComm_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_twt_proto_rawDescGZIP(), []int{0, 0}
}

type ProxyComm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mt         ProxyComm_MessageType `protobuf:"varint,1,opt,name=mt,proto3,enum=twtproto.ProxyComm_MessageType" json:"mt,omitempty"`
	Proxy      uint64                `protobuf:"varint,2,opt,name=proxy,proto3" json:"proxy,omitempty"`           // id of the proxy which is sending the message, must by globally unique
	Connection uint64                `protobuf:"varint,3,opt,name=connection,proto3" json:"connection,omitempty"` // sequential number of the connection on the local side of the proxy
	Seq        uint64                `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`               // sequential number of the message within the connection, sequential numbers are independent per up/down directions
	Address    string                `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`        // remote address to connect to, only used in OPEN_CONN message
	Port       uint32                `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`             // remote port to connect to, only used in OPEN_CONN message
	Data       []byte                `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`              // data chunk, only used in DATA_* messages
}

func (x *ProxyComm) Reset() {
	*x = ProxyComm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyComm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyComm) ProtoMessage() {}

func (x *ProxyComm) ProtoReflect() protoreflect.Message {
	mi := &file_twt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyComm.ProtoReflect.Descriptor instead.
func (*ProxyComm) Descriptor() ([]byte, []int) {
	return file_twt_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyComm) GetMt() ProxyComm_MessageType {
	if x != nil {
		return x.Mt
	}
	return ProxyComm_DATA_DOWN
}

func (x *ProxyComm) GetProxy() uint64 {
	if x != nil {
		return x.Proxy
	}
	return 0
}

func (x *ProxyComm) GetConnection() uint64 {
	if x != nil {
		return x.Connection
	}
	return 0
}

func (x *ProxyComm) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ProxyComm) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ProxyComm) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ProxyComm) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_twt_proto protoreflect.FileDescriptor

var file_twt_proto_rawDesc = []byte{
	0x0a, 0x09, 0x74, 0x77, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x77, 0x74,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xae, 0x02, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x43,
	0x6f, 0x6d, 0x6d, 0x12, 0x2f, 0x0a, 0x02, 0x6d, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1f, 0x2e, 0x74, 0x77, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79,
	0x43, 0x6f, 0x6d, 0x6d, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x02, 0x6d, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65,
	0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x66,
	0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a,
	0x09, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x44, 0x41, 0x54, 0x41, 0x5f, 0x55, 0x50, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x50, 0x45,
	0x4e, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x4c, 0x4f, 0x53,
	0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x5f, 0x53, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x4c,
	0x4f, 0x53, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x5f, 0x43, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04,
	0x50, 0x49, 0x4e, 0x47, 0x10, 0x05, 0x42, 0x14, 0x5a, 0x12, 0x6b, 0x65, 0x74, 0x72, 0x79, 0x2e,
	0x6e, 0x65, 0x74, 0x2f, 0x74, 0x77, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_twt_proto_rawDescOnce sync.Once
	file_twt_proto_rawDescData = file_twt_proto_rawDesc
)

func file_twt_proto_rawDescGZIP() []byte {
	file_twt_proto_rawDescOnce.Do(func() {
		file_twt_proto_rawDescData = protoimpl.X.CompressGZIP(file_twt_proto_rawDescData)
	})
	return file_twt_proto_rawDescData
}

var file_twt_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_twt_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_twt_proto_goTypes = []interface{}{
	(ProxyComm_MessageType)(0), // 0: twtproto.ProxyComm.MessageType
	(*ProxyComm)(nil),          // 1: twtproto.ProxyComm
}
var file_twt_proto_depIdxs = []int32{
	0, // 0: twtproto.ProxyComm.mt:type_name -> twtproto.ProxyComm.MessageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_twt_proto_init() }
func file_twt_proto_init() {
	if File_twt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_twt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyComm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_twt_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_twt_proto_goTypes,
		DependencyIndexes: file_twt_proto_depIdxs,
		EnumInfos:         file_twt_proto_enumTypes,
		MessageInfos:      file_twt_proto_msgTypes,
	}.Build()
	File_twt_proto = out.File
	file_twt_proto_rawDesc = nil
	file_twt_proto_goTypes = nil
	file_twt_proto_depIdxs = nil
}
